# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Please stop yelling online
email: harrison.bachrach@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Comics featuring people like shapes with text by Harrison Bachrach.
baseurl: "/psyo" # the subpath of your site, e.g. /blog
url: "harrisonbachrach.com" # the base hostname & protocol for your site
permalink: none
twitter_username: HarryB
github_username:  HarrisonB
future: true

# Build settings
markdown: kramdown
